In [1]:
sc.version

'3.1.3'

In [2]:
server_name = "jdbc:sqlserver://34.125.61.40"
database_name = "TestDB"
url = server_name + ";" + "databaseName=" + database_name + ";"

table_name = "Inventory"
username = "SA"
password = "Passw0rd123456" # Please specify password here

In [3]:
url

'jdbc:sqlserver://34.125.61.40;databaseName=TestDB;'

In [4]:
synthetic_df = spark.createDataFrame([{'name':'Aekanun','gender':'M','income':1333.4}\
                                      ,{'name':'Ornanong','gender':'F','income':3334.3}])

In [5]:
synthetic_df.show()

+------+------+--------+
|gender|income|    name|
+------+------+--------+
|     M|1333.4| Aekanun|
|     F|3334.3|Ornanong|
+------+------+--------+

In [6]:
synthetic_df.write.mode('overwrite').format("jdbc")\
        .option("url", url) \
        .option("dbtable", table_name) \
        .option("user", username) \
        .option("password", password)\
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver").save()

In [7]:
jdbcDF = spark.read.format("jdbc")\
        .option("url", url) \
        .option("dbtable", table_name) \
        .option("user", username) \
        .option("password", password)\
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")

In [8]:
raw_df = jdbcDF.load()

In [9]:
raw_df.show()

+------+------+--------+
|gender|income|    name|
+------+------+--------+
|     F|3334.3|Ornanong|
|     M|1333.4| Aekanun|
+------+------+--------+

# Upload csv to mssql docker in vm

In [10]:
plant1_weather = spark.read.csv('gs://solar-data-deep-wares-377415/data/Plant_1_Weather_Sensor_Data.csv',header=True,inferSchema=True)
plant2_weather = spark.read.csv('gs://solar-data-deep-wares-377415/data/Plant_2_Weather_Sensor_Data.csv',header=True,inferSchema=True)
plant1_gen = spark.read.csv('gs://solar-data-deep-wares-377415/data/Plant_1_Generation_Data.csv',header=True,inferSchema=True)
plant2_gen = spark.read.csv('gs://solar-data-deep-wares-377415/data/Plant_2_Generation_Data.csv',header=True,inferSchema=True)

In [11]:
plant1_weather.show()

+-------------------+--------+---------------+-------------------+------------------+-----------+
|          DATE_TIME|PLANT_ID|     SOURCE_KEY|AMBIENT_TEMPERATURE|MODULE_TEMPERATURE|IRRADIATION|
+-------------------+--------+---------------+-------------------+------------------+-----------+
|2020-05-15 00:00:00| 4135001|HmiyD2TTLFNqkNe| 25.184316133333333|        22.8575074|        0.0|
|2020-05-15 00:15:00| 4135001|HmiyD2TTLFNqkNe|  25.08458866666667|22.761667866666663|        0.0|
|2020-05-15 00:30:00| 4135001|HmiyD2TTLFNqkNe| 24.935752600000004|22.592305533333334|        0.0|
|2020-05-15 00:45:00| 4135001|HmiyD2TTLFNqkNe|         24.8461304|22.360852133333335|        0.0|
|2020-05-15 01:00:00| 4135001|HmiyD2TTLFNqkNe| 24.621525357142858|22.165422642857145|        0.0|
|2020-05-15 01:15:00| 4135001|HmiyD2TTLFNqkNe| 24.536092200000002|21.968570866666667|        0.0|
|2020-05-15 01:30:00| 4135001|HmiyD2TTLFNqkNe| 24.638673866666664|22.352925666666668|        0.0|
|2020-05-15 01:45:00| 4135001|HmiyD2TTLFNqkNe| 24.873022333333335|        23.1609192|        0.0|
|2020-05-15 02:00:00| 4135001|HmiyD2TTLFNqkNe| 24.936930466666663|         23.026113|        0.0|
|2020-05-15 02:15:00| 4135001|HmiyD2TTLFNqkNe| 25.012247600000002|23.343229266666665|        0.0|
|2020-05-15 02:30:00| 4135001|HmiyD2TTLFNqkNe| 25.005149333333335|23.639459266666666|        0.0|
|2020-05-15 02:45:00| 4135001|HmiyD2TTLFNqkNe|  24.99301953333333|        24.0394858|        0.0|
|2020-05-15 03:00:00| 4135001|HmiyD2TTLFNqkNe| 25.016309428571425|24.384135571428573|        0.0|
|2020-05-15 03:15:00| 4135001|HmiyD2TTLFNqkNe| 24.985215266666664|24.351507733333335|        0.0|
|2020-05-15 03:30:00| 4135001|HmiyD2TTLFNqkNe| 24.937731933333332|24.060296533333336|        0.0|
|2020-05-15 03:45:00| 4135001|HmiyD2TTLFNqkNe| 24.879099533333335|23.709794133333336|        0.0|
|2020-05-15 04:00:00| 4135001|HmiyD2TTLFNqkNe| 24.678902199999996|22.589941533333334|        0.0|
|2020-05-15 04:15:00| 4135001|HmiyD2TTLFNqkNe|         24.3519308|21.783642533333335|        0.0|
|2020-05-15 04:30:00| 4135001|HmiyD2TTLFNqkNe|         24.0626222|21.852524933333335|        0.0|
|2020-05-15 04:45:00| 4135001|HmiyD2TTLFNqkNe| 24.013224200000003|         22.306315|        0.0|
+-------------------+--------+---------------+-------------------+------------------+-----------+
only showing top 20 rows

In [12]:
database_name = "SolarDB"
url = server_name + ";" + "databaseName=" + database_name + ";"

In [13]:
url

'jdbc:sqlserver://34.125.61.40;databaseName=SolarDB;'

In [14]:
plant1_weather.write.mode('overwrite').format("jdbc")\
        .option("url", url) \
        .option("dbtable", "plant1_weather") \
        .option("user", username) \
        .option("password", password)\
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver").save()

In [15]:
plant2_weather.write.mode('overwrite').format("jdbc")\
        .option("url", url) \
        .option("dbtable", "plant2_weather") \
        .option("user", username) \
        .option("password", password)\
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver").save()

In [16]:
plant1_gen.write.mode('overwrite').format("jdbc")\
        .option("url", url) \
        .option("dbtable", "plant1_gen") \
        .option("user", username) \
        .option("password", password)\
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver").save()

In [17]:
plant2_gen.write.mode('overwrite').format("jdbc")\
        .option("url", url) \
        .option("dbtable", "plant2_gen") \
        .option("user", username) \
        .option("password", password)\
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver").save()